### ISSUE TITLE
Conversion to html does not extract images

### ISSUE THREAD

**Issue by Deyrajesh** [mlocati/chm-lib#4]
I have been trying to convert a chm file to html. it is converting but I cant extract images from that .chm. Image path is generating. And some image files totally broke down to some unreadable code. After the images all the contents of the .chm file got over lined.

**Comment by mlocati** [comment]
@Deyrajesh could you provide the affected CHM? If it's a problem to share it publicly, you can send me an email (I obviously won't share it).

**Comment by Deyrajesh** [comment]
do you please suggest me any link where i can download small chm files. I
cant find any one. I am sending you my google drive url.

https://drive.google.com/open?id=0B43wIj3MQJjtQ1dfaENsTHhsSUE

**Comment by mlocati** [comment]
You can see my email address on GitHub: for instance [here](https://github.com/mlocati/chm-lib/commit/8b05d7b8a0eb5b56f8840d57e3c079fd3af02eaf.patch)

**Comment by Deyrajesh** [comment]
Sir I have mailed you on that id. Please acknowledge me so I delete this links from here

**Comment by mlocati** [comment]
File downloaded, thanks!

**Comment by mlocati** [comment]
I wrote this code:

```php
<?php

use CHMLib\CHM;
use CHMLib\Entry;

require_once 'CHMLib.php';

$outputFolder = dirname(__FILE__) . DIRECTORY_SEPARATOR . 'out';
if (!is_dir($outputFolder)) {
    mkdir($outputFolder);
}
$chm = CHM::fromFile('sekhelp.chm');
foreach ($chm->getEntries(Entry::TYPE_FILE) as $entry) {
    echo "Processing {$entry->getPath()}... ";
    $entryPath = ltrim(str_replace('/', DIRECTORY_SEPARATOR, $entry->getPath()), DIRECTORY_SEPARATOR);
    $parts = explode(DIRECTORY_SEPARATOR, $entryPath);
    $subfolder = count($parts) > 1 ? implode(DIRECTORY_SEPARATOR, array_splice($parts, 0, -1)) : '';
    $filename = array_pop($parts);
    $path = $outputFolder;
    if ($subfolder !== '') {
        $path .= DIRECTORY_SEPARATOR . $subfolder;
        if (!is_dir($path)) {
            mkdir($path, 0777, true);
        }
    }
    $path .= DIRECTORY_SEPARATOR . $filename;
    file_put_contents($path, $entry->getContents());
    echo "done.\n";
}
```

and everything seems to work fine. What's your exact problem?

**Comment by Deyrajesh** [comment]
I am sending my problem / screen shot on your email id sir.

**Comment by Deyrajesh** [comment]
Sir your code worked . :) thank you so much. I forgot to use that "CHMLib\Entry" file. Now its working perfectly. Thank you so much sir. I have not find anything on web regarding this. But Your library that working parfectly. Thank you again sir.

**Comment by mlocati** [comment]
No problems! [I added the sample code](https://github.com/mlocati/chm-lib/commit/6828199f7d067975e69e13753823717b87c2debe) to the README.md file: it may be handy for others too.

**Comment by Deyrajesh** [comment]
Thank you. It will be very helpful to others also. Because there is no such lib on internet for this conversion.

**Comment by mlocati** [comment]
Well, a library exists: this one :wink:

**Comment by Deyrajesh** [comment]
Hello sir, I have been trying to convert the toc of the file to a separate
html file, but honestly  I dont have that much of skill to convert that
one. I hav successfully break the toc and print it on my browser with the
help of your code, But I cant able to fetch the urls of the link. Please
help me sir. Thank you sir.

**Comment by Deyrajesh** [comment]
`echo  str_repeat("\t", $level).print_r($child->getName(), 1)."\n";` prints the Content names, but when I use `print_r($level)` or `print_r($child->getName())`, both of them prints some xml sting. I am confused how it is printing. Please help me to understand this one. Thank you sir.

**Comment by mlocati** [comment]
It should be quite easy: when you extract the files, you store the `$entry->getPath()` in a dictionary.

Then, when you read the toc, you can determine the item you saved before by using `$child->getLocal()`:

Using the examples in the README.md, you could have something like this:

```php
$dictionary = array();

// Extract the contents of the CHM file
// [omissis]
foreach ($chm->getEntries(Entry::TYPE_FILE) as $entry) {
    // [omissis]
    $path .= DIRECTORY_SEPARATOR . $filename;
    file_put_contents($path, $entry->getContents());
    $dictionary[$entry->$entry->getPath()] = $path;
}

// Read the TOC
function printTree($tree, $level)
{
    global $dictionary;
    if ($tree !== null) {
        foreach ($tree->getItems() as $child) {
            // [omissis]
            $filePath = isset($dictionary[$child->getLocal()])
                ? $dictionary[$child->getLocal()]
                : null; 
            // [omissis]
            printTree($child->getChildren(), $level + 1);
        }
    }
}
// [omissis]
```

**Comment by Deyrajesh** [comment]
sir I am facing "_Object of class CHMLib\Entry could not be converted to string_"  this fetal error while converting.
